
production:
  adapter: postgresql
  database: TicTakToe
  encoding: unicode
  pool: 5
  

development:
  adapter: postgresql
  encoding: unicode
  database: TicTakToe
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: TicTakToe
  pool: 5